### PR TITLE
link removido e copiado o ficheiro

### PR DESCRIPTION
**Pull request by andralves717**
Removi a criação do link para o `~/.local/bin` e simplesmente copiei o ficheiro.
Assim o utilizador pode apagar o git clone após a instalação

### CODE REVIEW

**Comment by tuxPT** [comment]
That isn't pratical if you need to update

**Comment by tuxPT** [comment]
Pull request refused because it isn't a issue

**Comment by andralves717** [comment]
> That isn't pratical if you need to update

./install.sh and updates, you don't need to have the meals-ua.py in random place on your pc

**Comment by RodrigoRosmaninho** [comment]
To me both your points are valid.
Maybe we could do this like [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) does it. Once installed it checks if there are updates everytime it runs. If there are, it asks the user for permission to update and automatically clones the repository, installs itself again, and removes the repo.

If we did it like that users would actually update. 
In that case we could install it like @andralves717 is proposing and not have to manually clone the repo and run the install script everytime there's an update.
cc @tuxPT @Jpfonseca

**Comment by RodrigoRosmaninho** [comment]
Reopened to allow for more discussion

**Comment by tuxPT** [comment]
Oh my zsh doesn't remove the repo, the repo is in .oh-my-zsh, you can install meals ua in a hidden folder if you want

**Comment by andralves717** [comment]
We have a line in meals-ua.py that indicates the actual version of the program
```

# Made possible by the University of Aveiro's public API

# VERSION 3

# Necessary imports
import urllib.request as urllib
import sys, os
import argparse
```

We can use that to update, when is different we can do `wget https://raw.githubusercontent.com/GLUA-UA/meals-ua/master/meals-ua.py`

**Comment by RodrigoRosmaninho** [comment]
> Oh my zsh doesn't remove the repo, the repo is in .oh-my-zsh, you can install meals ua in a hidden folder if you want

Then I was wrong, thanks

**Comment by andralves717** [comment]
> We have a line in meals-ua.py that indicates the actual version of the program
> 
> ```
> 
> # Made possible by the University of Aveiro's public API
> 
> # VERSION 3
> 
> # Necessary imports
> import urllib.request as urllib
> import sys, os
> import argparse
> ```
> 
> We can use that to update, when is different we can do `wget https://raw.githubusercontent.com/GLUA-UA/meals-ua/master/meals-ua.py`

we cant put `meals-ua.py` in `$HOME/.local/lib` and a shell script in `$HOME/.local/bin` to verify updates and execute `meals-ua.py`

**Comment by tuxPT** [comment]
I would suggest the oh my zsh approach
https://github.com/robbyrussell/oh-my-zsh/blob/master/tools/upgrade.sh

**Comment by tuxPT** [comment]
For the location of the executables you can see there https://www.freedesktop.org/software/systemd/man/file-hierarchy.html

**Comment by Jpfonseca** [comment]
> Removi a criação do link para o `~/.local/bin` e simplesmente copiei o ficheiro.
> Assim o utilizador pode apagar o git clone após a instalação

On this I think that the best place for the zsh script should be under `.oh-my-zsh/custom/plugins/` .

On the upgrade/update issue I think this is the best approach


> I would suggest the oh my zsh approach
> https://github.com/robbyrussell/oh-my-zsh/blob/master/tools/upgrade.sh

**Comment by tuxPT** [comment]
@Jpfonseca the install script was updated 2 months ago where I made it shell agnostic, there isn't any shell specific code, not even an alias in a zshrc file

**Comment by Jpfonseca** [comment]
Knowing the current stage of the project the best thing to do would be creating  a pip package and simply ship it through pip. 

If you want to keep the `ìnstall.sh`script, it would be better for it to be only using the pip version and  saving it on `$HOME/.local/lib/python3.7/site-packages/`, which is the default location of the `pip install -user ...` command .

For the package version I think we should reset the current version to be similar to the pip package one.

> > We have a line in meals-ua.py that indicates the actual version of the program
> > ```
> > 
> > # Made possible by the University of Aveiro's public API
> > 
> > # VERSION 3
> > 
> > # Necessary imports
> > import urllib.request as urllib
> > import sys, os
> > import argparse
> > ```
> > 
> > 
> > We can use that to update, when is different we can do `wget https://raw.githubusercontent.com/GLUA-UA/meals-ua/master/meals-ua.py`
> 
> we cant put `meals-ua.py` in `$HOME/.local/lib` and a shell script in `$HOME/.local/bin` to verify updates and execute `meals-ua.py`

**Pull request closed without merging**
